title: Production Matters
email: productionmattersblog@gmail.com
author: Robbie Edwards
description: >-
  Production Matters explores the intersection of process, people, and the business of games.
  Designed for producers who prioritize results over rituals, we provide deep-dive insights
  into optimizing game development cycles.

baseurl: ""
url: "https://productionmatters.co"

# Theme
theme: jekyll-theme-clean-blog

# Markdown (required for MathJax $$ syntax)
kramdown:
  input: GFM
  math_engine: mathjax

# Build settings
plugins:
  - jekyll-feed
